### ISSUE TITLE
Calling diagram syntheses instantiated with with the ReinitializingDiagramSynthesis may cause instance/injection problems in LS

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#121]
This occurs for example when switching between different compilation steps of SCCharts, then the synthesis itself may throw exceptions as below. Not appearing in the Eclipse implementation.
I am not sure yet if this is in fact an issue within KLighD or if the synthesis, but it seems to be related to the instanciation that KLighD does with the ReinitializinDiagramSynthesis.

First error:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.complete(AbstractRequest.java:65)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at de.cau.cs.kieler.sccharts.ui.synthesis.SCChartsSynthesis.lambda$0(SCChartsSynthesis.java:190)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:140)
	at de.cau.cs.kieler.sccharts.ui.synthesis.SCChartsSynthesis.getDisplayedActions(SCChartsSynthesis.java:192)
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.getDisplayedActions(ReinitializingDiagramSynthesisProxy.java:308)
	at de.cau.cs.kieler.klighd.ViewContext.getDisplayedActions(ViewContext.java:836)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.updateDiagramOptions(KGraphDiagramServer.java:237)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.prepareUpdateModel(KGraphDiagramServer.java:198)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:161)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:1)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 9 more
```
Second error that may occur:
```
java.util.concurrent.CompletionException: org.eclipse.elk.core.util.WrappedException: KLighD: Cannot instantiate de.cau.cs.kieler.sccharts.ui.synthesis.SCChartsSynthesis.
Is that class free of compiler errors?
Does it extend de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis?
See exception trace below.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.complete(AbstractRequest.java:65)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.elk.core.util.WrappedException: KLighD: Cannot instantiate de.cau.cs.kieler.sccharts.ui.synthesis.SCChartsSynthesis.
Is that class free of compiler errors?
Does it extend de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis?
See exception trace below.
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.getNewDelegateInstance(ReinitializingDiagramSynthesisProxy.java:258)
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.getDisplayedLayoutOptions(ReinitializingDiagramSynthesisProxy.java:337)
	at de.cau.cs.kieler.klighd.ViewContext.getDisplayedLayoutOptions(ViewContext.java:853)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.updateDiagramOptions(KGraphDiagramServer.java:230)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.prepareUpdateModel(KGraphDiagramServer.java:198)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:161)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:1)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 9 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: ConcurrentModificationException
  at SCChartsSynthesis.class(SCChartsSynthesis.java:1)
  while locating SCChartsSynthesis

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
SCChartsSynthesis:               "de.cau.cs.kieler.sccharts.ui.synthesis.SCChartsSynthesis"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.getNewDelegateInstance(ReinitializingDiagramSynthesisProxy.java:249)
	... 16 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:636)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.getNext(Iterators.java:845)
	at com.google.common.collect.Iterables.getFirst(Iterables.java:779)
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy$ViewSynthesisScope$1.get(ReinitializingDiagramSynthesisProxy.java:198)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	... 18 more

```

**Comment by NiklasRentzCAU** [comment]
Fixed with #131
