### ISSUE TITLE
"Widget disposed" exception when closing diagram view while layout running

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#16]
When a (long running) layout is triggered and the diagram view is closed before the layout finishes, an "Widgets has been disposed" exception is thrown.

Stacktrace:
```
org.eclipse.swt.SWTException: Widget is disposed
--
at org.eclipse.swt.SWT.error(SWT.java:4533)
at org.eclipse.swt.SWT.error(SWT.java:4448)
at org.eclipse.swt.SWT.error(SWT.java:4419)
at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
at org.eclipse.swt.widgets.Widget.addListener(Widget.java:199)
at de.cau.cs.kieler.klighd.piccolo.internal.KlighdCanvas$KlighdRoot.getDefaultInputManager(KlighdCanvas.java:142)
at de.cau.cs.kieler.klighd.piccolo.internal.KlighdCanvas.sendInputEventToInputManager(KlighdCanvas.java:223)
at de.cau.cs.kieler.klighd.piccolo.internal.events.KlighdMouseEventListener$1.run(KlighdMouseEventListener.java:169)



```

**Comment by NiklasRentzCAU** [comment]
This issue is migrated from the old KIELER Pragmatics JIRA issue tracker. See the old discussion on this ticket in [KIPRA-1898](https://rtsys.informatik.uni-kiel.de/jira/projects/KIPRA/issues/KIPRA-1898).
