### ISSUE TITLE
Change in SWT's Color as of v3.115.0.qualifier (platform v4.17)

### ISSUE THREAD

**Issue by sailingKieler** [kieler/KLighD#75]
The changes in `Color.equals(Object)` made in https://github.com/eclipse/eclipse.platform.swt/commit/6f25fa51112fbf1670baee56c085ab60273daf47#diff-d8955873b2f9151adfc7b26df9b20e504b4684bea8e0142ee7c96a94b155ca28L219-R361
contributed in https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/162994/
being part of https://github.com/eclipse/eclipse.platform.swt/releases/tag/R4_17
will on Win32 cause an unexpected early exit in https://github.com/eclipse/gef-legacy/blob/14563a9e1f2af636a5364d195cf07dbff6f35fa6/org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java#L1459-L1463 in case some disposed color object is compared to some color object denoting `white` color.

This is - on Win32 - because the color values as well as the `disposed` state are (now) encoded in the field `handle` only,
and `handle == -1 ==  0xFFFFFFFF` (disposed) equals `handle == 0x00FFFFFF` (white) in the rightmost 3 bytes as assessed in `Color.equals(Object)`, see link above.

This causes the drawing of the draw2d figures wrapped by [Draw2DNode](https://github.com/kieler/KLighD/blob/c878e1ff98642061ede4686da237bf8b0c031d8c/plugins/de.cau.cs.kieler.klighd.piccolo.draw2d/src/de/cau/cs/kieler/klighd/piccolo/draw2d/Draw2DNode.java#L182)s to break once any altered coloring is to be reverted to `white`. In those cases the previous - now disposed - color object is kept in the draw2d figure because of [the early exit](https://github.com/eclipse/gef-legacy/blob/14563a9e1f2af636a5364d195cf07dbff6f35fa6/org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java#L1664-L1668). The subsequent paint runs fail with a `Graphic is disposed` exception:
```
org.eclipse.swt.SWTException: Graphic is disposed
       at org.eclipse.swt.SWT.error(SWT.java:4869)
       at org.eclipse.swt.SWT.error(SWT.java:4784)
       at org.eclipse.swt.SWT.error(SWT.java:4755)
       at org.eclipse.swt.graphics.Color.getRGB(Color.java:410)
       at de.cau.cs.kieler.klighd.piccolo.draw2d.GraphicsAdapter.setForegroundColor(GraphicsAdapter.java:512)
       at org.eclipse.draw2d.Figure.paint(Figure.java:1112)
       ...
```

**Comment by sailingKieler** [comment]
This change is in production since end of 2021, and I didn't hear any complaints so it seems to be fine.
